<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    </ItemGroup>
    
    <ItemGroup>
      <_ContentIncludedByDefault Remove="PDF_folder\5242f47c-9b18-4335-833b-df06383ad989\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\53243a2c-03cd-446f-a432-2f68ca9ecc51\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\b81002cb-5df7-4f1c-a752-224d1ebf3372\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\1b43f8bd-aa84-407e-8d94-ec7edc78975b\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\3ed44fb3-16c2-4ea5-97a8-705b7502b29b\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\0fe2cbbb-e4df-4137-85a5-0b30c9fc3abd\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\5bd51b8b-74ea-4a90-a36b-bb1243ad357e\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\7d03029d-27d6-4abe-a0df-7a8350e57a6f\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\9bf4a0eb-d487-4636-b149-c42062c92d65\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\55d765d0-c107-4da3-b028-c602db9ebfc5\job.json" />
    </ItemGroup>

</Project>