<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>
    <ItemGroup>
      <_ContentIncludedByDefault Remove="PDF_folder\5242f47c-9b18-4335-833b-df06383ad989\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\53243a2c-03cd-446f-a432-2f68ca9ecc51\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\b81002cb-5df7-4f1c-a752-224d1ebf3372\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\1b43f8bd-aa84-407e-8d94-ec7edc78975b\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\3ed44fb3-16c2-4ea5-97a8-705b7502b29b\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\0fe2cbbb-e4df-4137-85a5-0b30c9fc3abd\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\5bd51b8b-74ea-4a90-a36b-bb1243ad357e\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\7d03029d-27d6-4abe-a0df-7a8350e57a6f\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\9bf4a0eb-d487-4636-b149-c42062c92d65\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\55d765d0-c107-4da3-b028-c602db9ebfc5\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\001bba78-d867-4d21-a1d2-20db90d07021\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\0054d10f-378a-4af3-8702-092356b258d0\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\059ed46c-8b39-46d3-93d6-02a31f40d46e\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\083ae25d-8bf3-4691-b14e-faf62874fbc3\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\0e23acb1-6c85-406e-ba88-eaf4e6329701\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\111283a6-6d2a-4d04-a972-90543f13347c\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\14dec047-859e-49c0-a100-51c428f691f9\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\1939218c-75d9-43bc-93c6-0cc9b380737e\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\26dd567a-dddd-4847-8455-f587d95d867e\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\2ac4b5b5-a6ff-43da-819e-3f9ebd46610a\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\2c44abac-047e-4319-a9ec-08d2aa7ebbc3\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\2cba76f9-74d3-45b5-8845-ddad16e3ee65\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\32ada91e-207b-44ca-abbe-b5190f5cd602\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\38d5c701-4bb4-4ef5-95fd-cabaebefb472\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\4986777e-fe7d-4bd7-87ab-db3ef0d45b33\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\5f3a2c36-38c2-4355-bc9b-bccaaccd1ce0\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\770fcfe4-f7a0-4029-bd39-216282592d21\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\7a4529ca-1e3c-48a0-b9bc-807c933fb9f5\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\a15a3cd6-e720-4f5d-98bf-ac60d1903cde\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\a7a6c9e3-98b2-467b-b3bb-34f4cc8c395c\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\a85afc65-8e1f-460f-817e-89b0e15b2ce6\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\aa5734d4-eee2-4fe9-80bf-51245cdd825d\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\ac8daaa5-f8d8-4485-a86e-c30a79cbf549\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\b749e0b2-6d38-404a-a3ea-7c2221ec293e\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\b79d1104-afb0-4356-abaa-90a66e6773a2\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\bea58b3a-9dd6-408c-bf67-624ed428fe50\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\bf7d9504-ce35-461b-915b-6c84be4b205a\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\cac6b0f4-e445-409c-9a71-60780edff4dd\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\fc5017ea-0816-49ca-a934-7c9849291770\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\fea58c57-9f90-4e87-95df-76b5483a9a54\job.json" />
      <_ContentIncludedByDefault Remove="PDF_folder\39a69d54-3c01-4126-b0e1-31f3b162058d\job.json" />
    </ItemGroup>

</Project>